name: "Build FAP"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build FAP
        id: build-app
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        with:
          sdk-channel: release # Options: dev, rc, release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build-app.outputs.suffix }}
          path: ${{ steps.build-app.outputs.fap-artifacts }}
